set nocompatible " vi incompatible mode
set encoding=UTF-8
set cursorline
set nu " line numbering is on
set wrap " line wrap
set lbr  " by word (not by charcter as by default)
set tabstop=4 " tab width measured in spaces
set shiftwidth=4
set autoindent
set expandtab
set colorcolumn=79
" displaying tab characters and trailing spaces
" with special characters \u2592\u2591 and \u2593
" They also may be '>-' and '@':
" :set listchars=tab:>-,trail:@
set lcs=tab:▒░,trail:▓
set list

set fo=tcq1
set hlsearch " highlighting results while searching

set grepprg=ack-grep

set path+=~/repogitories

"some stuff to get the mouse going in term
set mouse=a
set ttymouse=xterm2

" GUI
set guifont=DejaVu\ Sans\ Mono\ 12

" VUNDLE
filetype off
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

Bundle 'gmarik/vundle'
Bundle 'SirVer/ultisnips'
Bundle 'scrooloose/nerdtree'

Bundle 'godlygeek/csapprox'
Bundle 'vim-scripts/wombat256.vim'
Bundle 'altercation/vim-colors-solarized'
Bundle 'fugalh/desert.vim'
Bundle 'chriskempson/vim-tomorrow-theme'

filetype plugin indent on
" VUNDLE END

" Russian to English key mapping
set langmap=ФИСВУАПРШОЛДЬТЩЗЙКЫЕГМЦЧНЯ;ABCDEFGHIJKLMNOPQRSTUVWXYZ,фисвуапршолдьтщзйкыегмцчня;abcdefghijklmnopqrstuvwxyz

" colors
syntax on " syntax highlighting
syntax enable
let g:solarized_termcolors=256
let g:solarized_bold=1
let g:solarized_italic=1
let g:solarized_underline=1
let g:solarized_contrast="high"
set background=light
colorscheme solarized "desert

" NURDTREE
let NERDTreeIgnore=['\.pyc$', '\~$']
" NURDTREE END

" directory where the swap files are stored
set dir=~/.vim/temp/,$HOME/Local\ Settings/Temp
" directory where the backup files are stored
set backupdir=~/.vim/temp/,$HOME/Local\ Settings/Temp

autocmd vimenter * if !argc() | NERDTree | endif
map <C-n> :NERDTreeToggle<CR>
