export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"

# Эти команды должны выполняться в самом конце не только этого
# скрипта, но и всего скрипта интерактивной оболочки ~/.bashrc,
# поскольку тут будут финальные манипуляции с PATH.
if command -v pyenv 1>/dev/null 2>&1
then
    eval "$(pyenv init -)"
fi
