[ -z "$TMUX" ] && export TERM=xterm-256color
[[ $- = *i* ]] && source ~/.liquidprompt/liquidprompt

export WORKON_HOME=~/virtualenvs
mkdir -p $WORKON_HOME
source /usr/local/bin/virtualenvwrapper.sh

source $HOME/.cargo/env
