# Поддержка 256-цветного режима в tmux
[ -z "$TMUX" ] && export TERM=xterm-256color

# Включение liquidprompt только для интерактивных оболочек
[[ $- = *i* ]] && source ~/.liquidprompt/liquidprompt

# Редактор по умолчанию
export EDITOR=vi

# Настройки для virtualenv и virtualenvwrapper
#export WORKON_HOME=~/virtualenvs
#mkdir -p $WORKON_HOME
#source /usr/local/bin/virtualenvwrapper.sh

# Возоможность исполнять файлы из вселенной rust
source $HOME/.cargo/env

# Возоможность исполнять пакеты yarn
test -n "$(which yarn)" && export PATH="$(yarn global bin):$PATH"

# Средства быстрого изменения цветовой темы окружения
source $HOME/repogitories/dotfiles/alacritty/bashrc

# Автокомплит для pipenv
source $HOME/repogitories/dotfiles/pipenv/bashrc


###############  Важно!!!  ######################
# Этот фрагмент должен обязательно идти         #
# в самом конце, чтобы pyenv работал правильно. #
#################################################
# Активация pyenv
source $HOME/repogitories/dotfiles/pyenv/bashrc
